[packages.darwin]
brews = [
  "aria2",
  "asdf",
  "bat",
  "croc",
  "curl",
    "dua-cli",
  "eza",
  "fd",
  "fzf",
  "findutils",
  "gh",
  "git",
  "git-lfs",
  "neovim",
  "ripgrep",
  "thefuck",
  "tmux",
  "zoxide"
]

casks = [
  "font-hack-nerd-font",
  "iterm2",
  "orbstack"
]
